### ISSUE TITLE
mitsuhiko/textmate-jinja2 cannot be found!

### ISSUE THREAD

**Issue by olivierdb** [mitsuhiko/jinja2#124]
I can't seem to find the Jinja2 Textmate bundle anywhere!

Anyone know where I can find it?

**Comment by FractalizeR** [comment]
It seems, like docs saying, that it is available from `ext` folder needs to be corrected.

**Comment by ioab** [comment]
The file is still missing. It would be better to link to the bundle repository.

**Comment by mitsuhiko** [comment]
Can someone send a pull request for this?

**Comment by mitsuhiko** [comment]
Thanks. applied.

**Comment by ioab** [comment]
Okay. I submitted one.

**Comment by ioab** [comment]
You're welcome.
