### ISSUE TITLE
python 2 / 3 

### ISSUE THREAD

**Issue by kooky** [mitsuhiko/jinja2#349]
What is the view on python 2/3  compatibility?

Bit of an example from tests.py.  I was wonder if if it should be written this way so that it works in both python2 and python3.  Python3 has no long type.

    def test_number(value):
        """Return true if the variable is a number."""
        try:
             return isinstance(value, (int, float, long, complex, decimal.Decimal))
        except NameError:
            """No long in python3"""
            return isinstance(value, (int, float, complex, decimal.Decimal))

**Comment by ThiefMaster** [comment]
Kind of obsolete. The current test doesn't check for `long` anymore. However, that means it checks for different values in Python 2 and Python 3 which is probably not very good...

**Comment by ThiefMaster** [comment]
Just for reference, this is fixed by #406 / c6c6ea14375db6fb6a23a8bca533a6e388356422
