### ISSUE TITLE
Missing Wheel package format !?

### ISSUE THREAD

**Issue by stonebig** [mitsuhiko/jinja2#366]
Hello,

I see you have wheel support in your setup.cfg, but you didn't upload any .wheel package to Pypi.

Could you consider doing it ?
````
python setup.py sdist bdist_wheel upload -r pypi
````

**Comment by hayd** [comment]
Bump! It would be great to push a wheel for the last release (especially if a release is not planned soon).

**Comment by techtonik** [comment]
Wheel is there at https://pypi.python.org/pypi/Jinja2 so this issue can be closed.
