### ISSUE TITLE
Include and If Expressions

### ISSUE THREAD

**Issue by sbdchd** [mitsuhiko/jinja2#414]
When attempting to use if expressions with include the following error is thrown:
*TemplatesNotFound: Tried to select from an empty list of templates.*

The following setup works as expected:
    
    {% if self.title() != "Login" %}
	{% include 'message.html' %}
    {% endif %}

But when using include with if expressions like the following, the error is thrown.

    {% include 'message.html' if self.title() != "Login" %}

**Comment by davidism** [comment]
The second example is invalid syntax.  What made you think that was possible?

**Comment by sbdchd** [comment]
I thought it might work after looking through [if expressions](http://jinja.pocoo.org/docs/dev/templates/#if-expression) in the docs and seeing the following example.

    {% extends layout_template if layout_template is defined else 'master.html' %}

**Comment by davidism** [comment]
A [conditional expression](https://docs.python.org/3/reference/expressions.html#conditional-expressions) must contain an `else`; you've only written two thirds of the expression.

**Comment by cboos** [comment]
Note that the Jinja2 docs for [if expressions](http://jinja.pocoo.org/docs/dev/templates/#if-expression) also says:
> The else part is optional. If not provided, the else block implicitly evaluates into an undefined object:

So the include has to be completed that way, in your original example:
```html+jinja
{% include 'message.html' if self.title() != "Login" ignore if missing %}
```

**Comment by rjollos** [comment]
Before 2.11, in the Trac project we used the equivalent of:
```
{% include 'message.html' if self.title() != "Login" ignore missing %}
```

After #710 though, it seems the following must be used:
```
{% if self.title() != "Login" %}
{% include 'message.html' ignore missing %}
{% endif %}
```

I'm not sure it's possible to write an inline conditional statement with `ignore missing` after 2.11.

* [Trac #13242](https://trac.edgewall.org/ticket/13242).
