### ISSUE TITLE
Unable to open ipython3 notebook in pyhton 3.4. It gives "ImportError: No module named 'jinja2'"

### ISSUE THREAD

**Issue by SunilPatilGIT** [mitsuhiko/jinja2#417]
I am using python 3.4 in Ubuntu 14.04 LTS.
I have installed python 2.7, 3.4 and ipython and ipython3 from the Ubuntu software center.  I could open ipython notebook.

  I tried to use ipython3 notebook. But it gives "ImportError: No module named "'jinja2'. Ubuntu software center installed jinja2.

**Comment by untitaker** [comment]
This is very unlikely to be an issue with Jinja... please use the `#python` IRC channel on freenode, Stackoverflow or Reddit for support.
