### ISSUE TITLE
Support a context finalize

### ISSUE THREAD

**Issue by dstufft** [mitsuhiko/jinja2#431]
Jinja2 has the ability to configure a ``finalize`` function which will be called right before a value is finally rendered to do any last minute changes to the values. This hooks into the exact place that I need something, however it has one problem... it doesn't have access to the context.

Looking at the code, it appears that it wouldn't be very difficult to make the change so that the context is passed into the ``finalize`` function (infact I've got a proof of [concept branch](https://github.com/mitsuhiko/jinja2/compare/master...dstufft:contextfinalize)) but it has one major snag. If I understand the code, for nodes that can be rendered as a constant value the ``finalize`` function is called at compile time instead of at render time, which means that their is no context available at that time.

I see a few possible solutions to this problem:

* Add an ``Environment().contextfinalize`` function which is only called as a finalize function in the situations where we have a context available.
* Make the ``Environment().finalize`` function able to be decorated by the ``@contextfunction`` decorator, and pass ``None`` for the context if we're doing the finalize during the compilation step.
* Make the ``Environment().finalize`` function able to be decorated by the ``@contextfunction`` decorator, and disable the finalize during compilation step optimization if it wants a context.

Of these, I prefer passing a ``None`` as a context, this can degrade into the final option by simply raising an exception in the finalize function which will skip the optimization for that node and can be made to act like the first one by just doing a check for ``None`` and returning early in that case.

Thoughts?

**Comment by dstufft** [comment]
I went ahead and implemented this in #434 and verified it solves the problem I was having.

**Comment by untitaker** [comment]
I agree that opt. 2 is the most flexible and your PR seems reasonable, but what are you doing in `finalize` that requires the context?

**Comment by dstufft** [comment]
I have an object that represents a translated string but which requires access to the request in order to actually translate it. So without ``finalize`` I need to do something like this:

```
<p>{{ translation_string_obj.translate(request.translator) }}</p>
```

However, if I can access the context from within the finalize function, then I can write a finalize function like this:

```
@contextfunction
def translate_value(ctx, value):
    if isinstance(value, TranslationString):
        return value.translate(ctx["request"].translator)

    return value
```

which means that my template can be written like:

```
<p>{{ my_translate_string_obj }}</p>
```

and things will just work. All of the other solutions that I can come up with involve needing to either manually pass the translation string object through a translator filter or function inside of the template, or requires storing the current language inside of a thread local variable so that the finalize function can access it since it cannot access the context to get the request out of it.

**Comment by untitaker** [comment]
LGTM but this is out of my league, please make sb. else review this.

**Comment by dstufft** [comment]
Thanks a lot @mitsuhiko !
