### ISSUE TITLE
UndefinedError when using gettext inside a Macro

### ISSUE THREAD

**Issue by luanfonceca** [mitsuhiko/jinja2#438]
Hi folks, i am having a problem to use the `{{ _('Some String') }}` inside a macro, but outside the macro, in the templates it works. It is a known behavior?!
I am using `Jinja2==2.7.3` And the error message was: `UndefinedError: 'gettext' is undefined`

Thanks in advance.

**Comment by davidism** [comment]
http://jinja.pocoo.org/docs/dev/templates/#import-context-behavior

**Comment by luanfonceca** [comment]
Thanks for that @davidism!

o/
