### ISSUE TITLE
Overriding Variables of Outer Scopes

### ISSUE THREAD

**Issue by MrOrz** [mitsuhiko/jinja2#44]
In Jinja 1.2 there was a feature that allows us to override outer scope variables from within a inner scope, by adding an exclamation mark after the set statement.

This feature is somehow missing in Jinja2. However, such feature is often required. Here is a real-world example in stackoverflow:
http://stackoverflow.com/questions/4870346/can-a-jinja-variables-scope-extend-beyond-in-an-inner-block

It would be glad to see such feature back again in Jinja2 ; )

**Comment by dpgaspar** [comment]
+1

**Comment by dlenski** [comment]
Me too, could really use an override and it'd be great if the [template designer docs](http://jinja.pocoo.org/docs/dev/templates) explicitly mentioned this behavior!

I had to work with some data in an (admittedly horrible) format and was puzzled at why the followed pre-pass didn't work...

```
{% set last_one = none %}
{% for row in rows %}
	{% set last_one = row.field %}
{% endfor %}
```

I agree with @ruiposse's [comment](//github.com/mitsuhiko/jinja2/issues/44#issuecomment-38584401) that having a variable first set outside **all** loops reset itself inside them is very unexpected.

**Comment by t2y** [comment]
+1

**Comment by mitsuhiko** [comment]
I'm going to close this.  This cannot work in all cases in Jinja2 and I do not really wish on supporting it.
