### ISSUE TITLE
urlencode filter does not escape slashes

### ISSUE THREAD

**Issue by catharsis** [mitsuhiko/jinja2#444]
The driving function behind the urlencode filter (from jinja2/_compat.py)
````python
from urllib import quote as url_quote
````
doesn't escape slashes by default. This isn't documented (as far as I've been able to find) for the urlencode filter.

Is this intentional? If it's not, how about supplying a way to overriding the default behaviour or even make slash-escaping the default behaviour (although I expect that might be trickier, since it might break running code)? If it is intentional, documenting that fact would be helpful.

**Comment by catharsis** [comment]
Added a PR with suggestion on doc-change, if that's the way to go.

**Comment by untitaker** [comment]
The PR was closed through https://github.com/mitsuhiko/jinja2/commit/46acbf02ed9ab58c7a92553c95790e75bdc3c930, closing this too.
