### ISSUE TITLE
Temporary files aren't supported in Python3.4

### ISSUE THREAD

**Issue by joelfrederico** [mitsuhiko/jinja2#448]
Substituting a temporary file a la

    with temporaryfile.TemporaryFile() as fid:
        templatestream.dump(fid)

gives a crash: 

      File "/#################/python3.4/site-packages/jinja2/environment.py", line 1142, in dump
        fp.writelines(iterable)
    TypeError: 'str' does not support the buffer interface

**Comment by mitsuhiko** [comment]
Not a bug, you need to open the file in binary mode.
