### ISSUE TITLE
Support await/async keywords

### ISSUE THREAD

**Issue by sametmax** [mitsuhiko/jinja2#452]
New keywords are coming with Python 3.5 : https://www.python.org/dev/peps/pep-0492/

It would be useful to be able to use them in a jinja template, enabling async rendering of the template. Imagine an ORM implementing __await__ for it's attribute descriptor, then you could do:

```
  <ul>
  {% for comment in comments %}
    <li><a href="{{ await comment.author.url }}">{{ await comment.author.name }}</a></li>
  {% endfor %}
  </ul>
```

With "comments" being a lazy queryset.

This also open the door to generating the template lazyly as well, which is very useful for big templates.

The main problem I can see is that it suppose a different rendering process, because the rendering function must be a corouting itself, and must be scheduled in the event loop. So you can't use the original template.render(), and will need to provide a template.async_render() which will need to accept a backend, by default being asyncio.

**Comment by mitsuhiko** [comment]
Not going to happen for a wide variety of reasons, the biggest one being that it cannot actually be done in a sane way because of jinja being based on generators.  I also would like to see first how the uptake on this is before committing on supporting something I'm not using myself.

**Comment by sametmax** [comment]
Generators are compatible with await (https://www.python.org/dev/peps/pep-0492/#id43), you just have to wrap them in @coroutine. Plus, the idea is not to have one render() method doing both sync and async processing, it would mix paradigm and it wouldn't work.

It shoudln''t change the API, but add a separate rendering method : 

- a configuration hook to choose an async backend
- a arender() methode returning the deferred/future/promise implementation for this backend

I understand that if you don't use asynchronous web framework, it's will not appeal to you.

Honestly, jinja is fast enought that most of the time you don't need to care if it's blocking the event loop. Right now we by pass the fact it's synchronous by fetching the data asynchronously before, and the pass the result to the renderer.

The only time it's a problem is when : 

- you have caching, because you moved the data fetching outside of the template, any template caching solution becomes useless and you are forced to use a data caching solution. For small projects it's a bit overkill.
- you have very big templates, and you don't want to block the event loop for the whole template generation, but sill wish you could give some CPU time to a chunk or two here and there.

There is no hurry for this feature.

It's just that Jinja is the best template engine in Python, but we don't have any decent async way to render a template while JS has had it for years.

**Comment by amirouche** [comment]
> Not going to happen for a wide variety of reasons

http://jinja.pocoo.org/docs/2.9/api/#async-support
