### ISSUE TITLE
Named arguments in function call

### ISSUE THREAD

**Issue by ashep** [mitsuhiko/jinja2#460]
When a try to do something like this:
```html+django/jinja
{% set my_var = my_func('Some string', named_param='Another string') %}
```
I get the error: "'TokenStream' object has no attribute 'offset'".

**Comment by snoack** [comment]
I cannot reproduce this on 6bf78bc (current master/HEAD). Following code works just fine for me:

```python
env = jinja2.Environment()
tmpl = env.from_string("{% set my_var = my_func('Some string', named_param='Another string') %}")
tmpl.render(my_func=lambda *args, **kw: None)
```

```python
env = jinja2.Environment()
env.globals['my_func'] = lambda *args, **kw: None
tmpl = env.from_string("{% set my_var = my_func('Some string', named_param='Another string') %}")
tmpl.render()
```

Which version of jinja2 are you using? Where does `my_func` comes from (context, globals, etc.)? Do you use any extensions? Ideally, can you provide a piece of Python code (like my snippets above) to reproduce the issue?
