### ISSUE TITLE
TemplateSyntaxError: expected token 'end of print statement'

### ISSUE THREAD

**Issue by humiaozuzu** [mitsuhiko/jinja2#477]
This is the script inlined in HTML.
``` js
!function(){{var t=navigator.userAgent.match(/android/gi),e=navigator.userAgent.match(/iphone|ipod/gi),n=navigator.userAgent.match(/ipad/gi);/MicroMessenger/gi.test(navigator.userAgent)}e||n?document.getElementById("prompt").classList.add("ios-prompt"):t&&document.getElementById("prompt").classList.add("android-prompt")}(window,document);
```
Error raised when render

```
TemplateSyntaxError: expected token 'end of print statement', got 't'
```

**Comment by scharfmn** [comment]
Same issue
<textarea class="form-control linkbox" style="resize:none" rows="3" name="userpage|{{symbol['symbol']}}" id="feedback" placeholder="paste link here" required></textarea>

**Comment by ThiefMaster** [comment]
How is this a jinja issue? You have `{{` in your string which has a special meaning in Jinja.

**Comment by scharfmn** [comment]
It was my error. (I assume the other fellow who reported the issue made a
similar error.)
I tried to retract my comment; I guess it stuck.
Thank you very much for checking.

**Comment by ashishsingal1** [comment]
Weird, but this actually helped me. Thanks for posting it.
