### ISSUE TITLE
do_default function in filters.py fails jinja2.exceptions.UndefinedError

### ISSUE THREAD

**Issue by ruslantum** [mitsuhiko/jinja2#480]
do_default function in filters.py fails when value is a json dictionary with multiple subelements and parent element is undefined. Example:
nginx_epel_enabled|default(ansible_local.util.epel.enabled)|default(false)

Possible solution: wrap it with try exept to catch undefined for parent element and return default_value on exeption

**Comment by alvaroaleman** [comment]
Is it expected behaviour to have the ``default`` filter crash with a nullpointer exception?

Isn't it the whole point of that filter to catch such exceptions?

**Comment by virtuald** [comment]
+1, this was unexpected. At the very least, should have a documentation note about this.

**Comment by mitsuhiko** [comment]
It's not the function that is failing but the way you invoke it. The function cannot escape Jinja semantics. This cannot be changed.

**Comment by virtuald** [comment]
@mitsuhiko I didn't read his example above, I agree that it should break -- but what about this example?

    {{ missing.subelement|default('no') }}

This seems like it should work, and it does not.

**Comment by mitsuhiko** [comment]
That is not supposed to work with the default `Undefined` object.  You can make one that propagates undefineds further if you want.
