### ISSUE TITLE
Wrong syntax in example for range() function

### ISSUE THREAD

**Issue by micw** [mitsuhiko/jinja2#488]
The example for the built-in range function at http://jinja.pocoo.org/docs/dev/templates/#list-of-global-functions has wrong syntax:

{% for number in range(10 - users|count) %}

has to be:

{% for number in range(10, users|count) %}

**Comment by ThiefMaster** [comment]
The example is perfectly correct. It shows users and then adds empty items to have 10 items in the list.

**Comment by micw** [comment]
I see, you're right. I just misinterpreted it as "iterate 10...users|count" what it does not (and was not meant to do so).
