### ISSUE TITLE
'BoundField' object has no attribute '__call__'

### ISSUE THREAD

**Issue by mirzadelic** [mitsuhiko/jinja2#491]
Why am i getting error:
```
'BoundField' object has no attribute '__call__'
```

i use it with django:
```
{{ form.name(class="form-control") }}
```

view:
```
def cat_filter_form_tag(request, parent_category):
    form = SimpleCatFilterForm(parent_category, request.GET)
    return render(request, 'web/category_ads/filter_form.html', {"form": form})
```

**Comment by ThiefMaster** [comment]
You need to provide much more context/code.

**Comment by mirzadelic** [comment]
I modified post..
On this line i get that error:
```
{{ form.name(class="form-control") }}
```

Do you need more info?

**Comment by ThiefMaster** [comment]
That doesn't seem to be a Jinja problem. `form.name` doesn't seem to be callable.

**Comment by mirzadelic** [comment]
My form is:
```
class SimpleFilterForm(forms.Form):
    name = fields.CharField(label=_(Name'), required=False)
```

don't know what is wrong here?

**Comment by ThiefMaster** [comment]
You should probably ask this in a Django place. It's most likely not a Jinja issue...

**Comment by mirzadelic** [comment]
Ok, thanks.

**Comment by zoidbergwill** [comment]
Are you trying to override the `class` arg and sending it to `fields.CharField(label=_(Name'), required=False)`?
