### ISSUE TITLE
auto-close html tags in truncate filter

### ISSUE THREAD

**Issue by matthewrsj** [mitsuhiko/jinja2#506]
I am developing a web page with a slick slide show and ran into this issue with truncate:

In the front page slick slideshow, the five most recent blog posts are displayed in a carousel. Each slide contains the blog image and a summary. The summary is just the content truncated to 400 characters. This truncation is performed by a Jinja2 filter called ``truncate``. We use it like this:

```
{% set summary = article.content | truncate(400) %}
```

We use reStructuredText, which is pretty cool. It allows us to create bold and italic text using asterisks (*). To bold something, surround it by two asterisks on each side. To italicize something, surround it by one asterisk on each side. 

Problem
-------

Blog posts can be created with an opening set of asterisks in the first 400 characters, but no closing asterisks until after the first 400 characters. The summary now contains an opening tag with no closing tag. For some reason this causes our slide show to create an opening and a closing tag of the same type (for italics or for bold) and place it *after* the end of the summary.

Proposed Solution
-----------------

We can rewrite the Jinja2 `truncate` filter to close any opened tags. We could have an optional parameter (maybe `closetags=True`) that would tell `truncate` to close any HTML tags that were opened but not closed. 

This could probably done with some beautiful soup. If you don't want to use BS we could do a stack implementation. Add to stack when we see an opening tag, pop when we see that tag closed. If there is anything left on the stack at the end, pop it off and close it.

Thoughts?

**Comment by ThiefMaster** [comment]
Why not simply add another filter that tidies/sanitizes html (e.g. by closing unclosed tags)?

**Comment by matthewrsj** [comment]
@ThiefMaster that is a good solution. Is this a filter you would be interested in for Jinja2?

**Comment by ThiefMaster** [comment]
It sounds like something useful but personally I think it's not a good idea to include it in Jinja (I'm not a maintainer though) - you'd most likely use an existing library to cleanup the HTML and adding a new dependency for a rather specific filter (you only need it if you truncate strings containing HTML or deal with crappy HTML for some other reason) seems to be overkill.

**Comment by matthewrsj** [comment]
True, but if it is just an autoclose I could just implement a simple version of a stack and shouldn't need any new libraries.

**Comment by rbu** [comment]
I would seriously advise against writing your own HTML parser. If you need motivation: What about tags that do not need closing? What about script tags?

**Comment by mitsuhiko** [comment]
This filter really does not work on html input and Jinja2 will not gain an HTML parser.  I'm going to close this issue against Jinja2 here.

However maybe someone wants to make a pypi package that implements this.
