### ISSUE TITLE
Unclear 2.8 change about native strings in Python 2.7

### ISSUE THREAD

**Issue by techtonik** [mitsuhiko/jinja2#511]
[CHANGES](https://github.com/mitsuhiko/jinja2/blob/master/CHANGES) for 2.8 contains the following story:

> - Changed how Jinja2 enforces strings to be native strings in
  Python 2 to work when people break their default encoding.

What does it mean exactly? Does that mean that the proper fix for that -https://stackoverflow.com/questions/28642781/hack-jinja2-to-encode-from-utf-8-instead-of-ascii - is now possible?

**Comment by mitsuhiko** [comment]
No, I don't think that works still.  However it now explicitly only does some of it's behavior in the ascii range instead of relying on `str()` working in ascii only.  Jinja requires unicode strings and assumes the default encoding ascii in Python 2 for coercion. Everything outside of that is unsupported. I am not sure what this change means with regards to what roundup does.

**Comment by mitsuhiko** [comment]
The issue in question is #304 btw.

**Comment by techtonik** [comment]
@mitsuhiko thanks for the quick reply. The Roundup does nothing except that is passes 'utf-8' encoded string to Jinja2. The traceback is in the 2nd message here - http://issues.roundup-tracker.org/issue2550811

I wonder if it is possible to subclass unicode object that Jinja2 uses, to override concatenation and addition methods to get control over encoding conversion back to Jinja2?

**Comment by mitsuhiko** [comment]
> I wonder if it is possible to subclass unicode object that Jinja2 uses, to override concatenation and addition methods to get control over encoding conversion back to Jinja2?

The main issue that jinja encounters there is that it uses different tricks for unicode conversion.  For instance it uses `u''.join((a, b, c))` and `u'%s%s' % (a, b)`.  Those should use the default encoding so it's just a question to align the others.  But as I do not really care that much about this it would need patches and I would only accept them if it does not degrade performance too much.

**Comment by techtonik** [comment]
`u''.join((a, b, c))` is the same as `'' + a + b +c`, and internally it should be handled by the same `unicode.__add__` method. The only problem is that I do not see where is the source code for this class in Python.

> I would only accept them if it does not degrade performance too much.

How do you validate the performance? Are there some CI tests for that?

**Comment by mitsuhiko** [comment]
There used to be tests but because those internals have not been touched in ages it no longer exists.  There are some manual tests you can run though in the examples folder I think.
