### ISSUE TITLE
Fix capitalization on Jinja’s website

### ISSUE THREAD

**Issue by roryokane** [mitsuhiko/jinja2#514]
On http://jinja.pocoo.org/:

> ### Wide Range of Features
> * Sandboxed execution mode. Every aspect of the template execution is monitored and explicitly whitelisted or blacklisted, whatever is preferred. This makes it possible to execute untrusted templates.
> * powerful automatic HTML escaping system for cross site scripting prevention.
> * Template inheritance …

“powerful” should be capitalized. Otherwise it is hard to notice that a new bullet point starts there.

The text for the website doesn’t seem to be in the repository, or I would have made a pull request.

**Comment by mitsuhiko** [comment]
Fixed in d5077a0b148d52572d886726bef7647b51978d95
