### ISSUE TITLE
no test named 'None'

### ISSUE THREAD

**Issue by jakirkham** [mitsuhiko/jinja2#520]
Running into an issue where using a template like this `{{"" if np is None else np}}`, I get the following exception `jinja2.exceptions.TemplateAssertionError: no test named 'None'`. Trying with `is not` has similar problems.

**Comment by ThiefMaster** [comment]
Use lowercase `none`.

**Comment by jakirkham** [comment]
Thanks @ThiefMaster. I'm still pretty new to `jinja`, but it seems pretty cool. Thanks for the pointers too.
