### ISSUE TITLE
'bool' object is not callable: self._uptodate() in jinja2.8

### ISSUE THREAD

**Issue by xavierhardy** [mitsuhiko/jinja2#559]
There's a typo in `environment.py`:
```py
    @property
    def is_up_to_date(self):
        """If this variable is `False` there is a newer version available."""
        if self._uptodate is None:
            return True
        return self._uptodate()
```

It should be `_uptodate` instead of `_uptodate()` in the last line. I have an error when `_uptodate` is `False`.

Please fix, thanks.

**Comment by ThiefMaster** [comment]
Not a bug, `self._uptodate` is supposed to be a callable. See e.g. https://github.com/mitsuhiko/jinja2/blob/master/jinja2/loaders.py#L285

**Comment by xavierhardy** [comment]
So why is it not a callable in my case? Shouldn't it check that it is a boolean?

**Comment by ThiefMaster** [comment]
Which loader are you using?

**Comment by xavierhardy** [comment]
A custom loader fetching the template from an API.

**Comment by ThiefMaster** [comment]
Then you should return `lambda: whatever` for uptodate ;)

**Comment by ThiefMaster** [comment]
Also, just as a heads-up: Make sure you trust whatever API you get the template from. Being able to control the contents of a template gives you the ability to execute arbitrary pthon code unless you use a sandboxed environment!

**Comment by xavierhardy** [comment]
OK, I wasn't the one who implemented it, I just checked the FileSystemLoader code. Indeed, you're right. Sorry, for bothering you.

**Comment by xavierhardy** [comment]
Yes, we have already thought about that, we're already using the sandbox, just giving access to a few functions/classes.

**Comment by xavierhardy** [comment]
By the way, that was pretty fast, thanks ;)
